Description: Create an EC2 instance and a SG attached to the network interface

Parameters:
  defaultVpcId:
    Type: AWS::EC2::VPC::Id
  randomSubnetId:
    Type: AWS::EC2::Subnet::Id
  myAmiId:
    Type: AWS::EC2::Image::Id
  myKeyPairId:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instance
      VpcId: !Ref defaultVpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 32766
        CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref myAmiId
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref randomSubnetId
          GroupSet:
            - Ref: EC2InstanceSecurityGroup
      KeyName: !Ref myKeyPairId
      UserData:
       Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
